collections:
    posts:
        output: true
        permalink: /:categories/:year/:title/

permalink: /:categories/:title/

title: Brayan López
email: brxyxn.corp@live.com
description: >
    Diseñador Web, Desarrollador de Software
    Cursos, Tutoriales y Guías de Programación
baseurl: ""
url: "https://brxyxn.xyz"
lang: es
host: "localhost"
port: 4000
# Redes Sociales [Variables]
twitter_username: brxyxmp
facebook_username: brxyxmp
github_username: brxyxncorp
youtube_username: brxyxmp

theme: ultra-minimalista
exclude:
    - Gemfile
    - Gemfile.lock




# Definiendo Valores por Defecto
defaults:
-
    scope:
        path: ""
    values:
        layout: "post"
        title: "Brxyxn"
        author: "Brayan López"
        excerpt_separator: <!--more-->
-
    scope:
        path: "projects"
        type: "pages" # previously `page` in Jekyll 2.2.
    values:
        layout: "post" # overrides previous default layout
        author: "Brayan López"